name: act-build 

jobs:
  act-linux:
    if: $GITHUB_ACTIONS == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: apt-get update
    - run: apt install sudo
    - run: sudo apt -y install gcc-arm-none-eabi make openocd git
    - run: make build
